version: '3.9'

services:
  mysql:
    image: mysql:8.0.43-debian 
    container_name: mysql_spendtracker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spendtracker_db
      MYSQL_USER: spendtracker_user
      MYSQL_PASSWORD: spendtracker_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spendtracker_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  mysql_data:

networks:
  spendtracker_net:
    driver: bridge
